'use client';
import {useEffect,useState,useCallback} from 'react';
type Item=Record<string,any>;
const human=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const time=(s:string|number)=>s?new Date(s).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const statusClass=(s:string)=>['executed','accepted','completed'].includes(s)?'green':['denied','execution_failed','failed'].includes(s)?'red':['deferred','pending','stale','interrupted'].includes(s)?'amber':'neutral';
export default function Home(){
 const [state,setState]=useState<Item|null>(null),[tab,setTab]=useState('Findings'),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Item|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[scope,setScope]=useState('documents'),[execute,setExecute]=useState(false),[patientId,setPatientId]=useState(''),[pending,setPending]=useState(false);
 const api=async(path:string,body?:unknown)=>{const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;};
 const refresh=useCallback(async()=>{try{setState(await api('state'));setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void refresh();void api('health').then(refresh).catch(e=>setError(e.message));const t=setInterval(refresh,4000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{if(!selected){setDetail(null);return;}void api('findings/'+selected).then(setDetail).catch(e=>setError(e.message));},[selected,state]);
 async function action(path:string,body:unknown,label:string){setPending(true);try{await api(path,body);setNotice(label);await refresh();}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 const findings:Item[]=state?.findings||[];const runs:Item[]=state?.runs||[];const active=runs.find(r=>r.status==='running');
 const filtered=findings.filter(f=>(filter==='all'?f.status!=='superseded':f.status===filter)&&`${f.patientName} ${f.patientId} ${f.title} ${f.code}`.toLowerCase().includes(query.toLowerCase()));
 const f=detail?.finding;
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="/"><span className="brandmark">✳</span><span>PGx <strong>Watch</strong></span></a><div className="workspace">ANIMA SIMULATION <span>↗</span></div><nav>{['Findings','Activity','Rules','Automation'].map((name,i)=><button key={name} className={tab===name?'nav active':'nav'} onClick={()=>{setTab(name);setSelected(null);}}><span>{['◈','≋','⊞','◷'][i]}</span>{name}{name==='Findings'&&<small>{findings.length}</small>}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><i className={state?.connection?'dot':'dot off'}/>{state?.connection?'Simulator connected':'Awaiting connection'}</div><p>Evidence reviewer → GP reviewer<br/>→ Simulator execution</p><span className="simulation-tag">Synthetic patients only</span></div></aside>
  <main><header><div className="breadcrumb">Clinical intelligence <span>/</span> Pharmacogenetics</div><div className="header-right"><span className="live-dot"/> BACKEND AGENTS <span className="avatar">GP</span></div></header>
  <section className="content"><div className="title-row"><div className="eyebrow">CONTINUOUS MEDICATION REVIEW</div><span className="version">POLICY v1.0</span></div><div className="heading"><div><h1>{tab==='Findings'?'The right action. With the evidence.':tab==='Activity'?'Every decision, accounted for.':tab==='Rules'?'A policy the agents can follow.':'Keep watch as the world changes.'}</h1><p>{tab==='Findings'?'Patient-specific findings, independent GP review, and a clear record of what changed.':tab==='Activity'?'Follow scans, agent decisions, and confirmed simulator writes.':tab==='Rules'?'Twelve pharmacogenetics rules. Applied to evidence, never to a patient ID alone.':'Run manually, on a schedule, or when new simulator events arrive.'}</p></div></div>
  {error&&<div className="message error" role="alert">{error}<button onClick={()=>void refresh()}>Reconnect</button></div>}{notice&&<div className="message" role="status">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
  <div className="metrics"><div><span>Patients reviewed</span><strong>{(state?.patientsScanned||0).toLocaleString()}</strong><small>Across recorded scans</small></div><div><span>Findings identified</span><strong>{findings.filter(f=>!['excluded','superseded'].includes(f.status)).length}<em className="amber-text">{findings.filter(f=>f.severity==='high').length} high priority</em></strong><small>Supported by source records</small></div><div><span>GP accepted</span><strong>{findings.filter(f=>f.decision?.decision==='accept').length}</strong><small>Independently reviewed</small></div><div><span>Actions completed</span><strong>{(state?.actions||[]).filter((a:Item)=>a.status==='completed').length}<span className="tiny-check">✓</span></strong><small>Confirmed by the simulator</small></div></div>
  <div className="scanbar"><div><span className={active?'pulse dot':'dot'}/><strong>{active?active.phase:'Ready for the next review'}</strong><small>{active?`${active.scanned} of ${active.total} patients · ${active.errors.length} errors`:runs[0]?`Last scan ${human(runs[0].status)} · ${time(runs[0].startedAt)}`:'Start with all available PGx correspondence'}</small></div><div className="scan-controls"><select aria-label="Scan scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="documents">PGx correspondence</option><option value="sample">Sample cohort</option><option value="all">All patients · full scan</option><option value="patient">One patient</option></select>{scope==='patient'&&<input aria-label="Patient ID" placeholder="SIM-000051" value={patientId} onChange={e=>setPatientId(e.target.value)}/>}<label className="toggle-label"><input type="checkbox" checked={execute} onChange={e=>setExecute(e.target.checked)}/>Execute GP-accepted actions</label><button className="primary" disabled={pending||state?.busy||!!active||!state} onClick={()=>void action('scans',{scope,execute,...(scope==='patient'?{patientId}:{})},'Scan started. Findings appear as patients are reviewed.')}>{active?'Review in progress':'Run review'} <span>↗</span></button></div></div>
  {tab==='Findings'&&<><div className="section-heading"><h2>Review workspace <span>{filtered.length}</span></h2><div className="filters"><input aria-label="Search findings" placeholder="Search patient, gene, or action…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter findings" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All outcomes</option>{['accepted','executed','denied','deferred','excluded','pending','execution_failed','stale','superseded'].map(s=><option key={s} value={s}>{human(s)}</option>)}</select></div></div>
  <div className={'review-grid '+(f?'with-detail':'')}><div className="finding-list"><div className="table-label"><span>PATIENT & FINDING</span><span>GP OUTCOME</span></div>{filtered.length?filtered.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={'finding '+(selected===item.id?'selected':'')}><span className={'priority-bar '+item.severity}/><div className="finding-main"><div className="patient"><strong>{item.patientName}</strong><span>{item.patientId}</span></div><h3>{item.title}</h3><p>{human(item.code)} <span>·</span> {item.specialist}</p></div><div className="finding-meta"><span className={'badge '+statusClass(item.status)}>{human(item.status)}</span><small>{item.evidence.length} source references <span>→</span></small></div></button>):<div className="empty"><span>◈</span><h3>{query||filter!=='all'?'No matching findings':'Your evidence workspace is ready'}</h3><p>{query||filter!=='all'?'Try another search or outcome.':'Run a review to see patient findings and GP decisions here.'}</p></div>}</div>
  {f&&<aside className="detail"><div className="detail-top"><span className="eyebrow">CASE REVIEW</span><button aria-label="Close case" onClick={()=>setSelected(null)}>×</button></div><h2>{f.patientName}</h2><p className="muted">{f.patientId} · {f.title}</p><div className="detail-section"><label>01 · POLICY ACTION</label><p>{f.action}</p>{f.source&&<a href={f.source} target="_blank" rel="noreferrer">View guideline ↗</a>}</div><div className="detail-section"><label>02 · SOURCE EVIDENCE</label>{f.evidence.map((e:Item,i:number)=><blockquote key={i}><p>“{e.quote}”</p><cite>{e.resourceId} · version {e.version}</cite></blockquote>)}{!f.evidence.length&&<p>Test evidence excluded from clinical recommendations.</p>}</div>{f.warnings.length>0&&<div className="caution"><strong>Record context</strong>{f.warnings.map((w:string,i:number)=><p key={i}>{w}</p>)}</div>}<div className="detail-section"><label>03 · INDEPENDENT GP REVIEW</label>{f.decision?<><span className={'badge '+statusClass(f.status)}>{f.decision.decision}</span><p>{f.decision.rationale}</p></>:<p>{f.status==='excluded'?'No GP action required.':'Awaiting review.'}</p>}</div><div className="detail-section"><label>04 · SIMULATOR ACTIONS</label>{detail?.actions?.length?detail.actions.map((a:Item)=><div className="action-item" key={a.id}><span className={'badge '+statusClass(a.status)}>{a.status}</span><p>{human(a.body.type)}</p><small>{a.response?.id||a.response?.resource?.id||a.response?.resourceId||a.requestId}</small></div>):<p>No simulator writes for this finding.</p>}</div><div className="detail-buttons">{['accepted','execution_failed','executing'].includes(f.status)&&<button className="primary" disabled={pending||state?.busy} onClick={()=>void action(`findings/${f.id}/execute`,{},'Execution queued. The backend will recheck the current record.')}>Execute accepted actions</button>}{f.status!=='excluded'&&<button className="secondary" disabled={pending||state?.busy} onClick={()=>void action(`findings/${f.id}/review`,{execute:false},'Fresh evidence and GP review queued.')}>Re-review current record</button>}</div></aside>}</div></>}
  {tab==='Activity'&&<div className="activity-layout"><section className="panel"><h2>Scan history</h2>{runs.length?runs.map(r=><div className="history-item" key={r.id}><div><strong>{human(r.scope)} review</strong><span className={'badge '+statusClass(r.status)}>{human(r.status)}</span></div><p>{r.scanned} / {r.total} patients · {r.findings} findings · {r.trigger} · {r.execute?'execute accepted':'review only'}</p><small>{time(r.startedAt)}</small>{r.errors.map((e:Item,i:number)=><p className="red-text" key={i}>{e.patientId}: {e.message}</p>)}{r.scope==='all'&&['interrupted','failed','completed_with_errors'].includes(r.status)&&<button className="secondary" disabled={state?.busy} onClick={()=>void action(`runs/${r.id}/resume`,{},'Full scan resumed from its last completed page.')}>Resume scan</button>}</div>):<p className="muted">No scans yet.</p>}</section><section className="panel"><h2>Audit trail</h2>{(state?.events||[]).map((e:Item)=><details className="event" key={e.seq}><summary><span className="event-dot"/><strong>{human(e.type.replaceAll('.',' '))}</strong><small>{time(e.time)}</small></summary><pre>{JSON.stringify(e.data,null,2)}</pre></details>)}</section></div>}
  {tab==='Rules'&&<div className="rules-grid">{(state?.rules||[]).map((r:Item)=><article className="rule-card" key={r.id}><div><span className="eyebrow">{r.gene}</span><span className={'badge '+(r.severity==='high'?'amber':'neutral')}>{r.severity}</span></div><h2>{r.result}</h2><p className="rule-drug">{r.drug} · {r.context}</p><code>{r.code}</code><p>{r.action}</p><footer><span>{r.specialist}</span>{r.source&&<a href={r.source} target="_blank" rel="noreferrer">Guideline ↗</a>}</footer></article>)}</div>}
  {tab==='Automation'&&state&&<Automation settings={state.settings} disabled={pending} save={s=>action('settings',s,'Automation settings saved.')} />}
  <footer className="page-footer"><span>PGx Watch <b>·</b> Anima simulation workspace</span><span>Source evidence first. Every write traceable.</span></footer></section></main>
 </div>;
}
function Automation({settings,save,disabled}:{settings:Item;save:(s:Item)=>void;disabled:boolean}){const [s,setS]=useState(settings);return <div className="automation panel"><div className="eyebrow">TRIGGERS & EXECUTION</div><h2>Choose how the agents work</h2><p>Automation runs in the backend while the service is online. Settings persist across restarts.</p><label className="setting"><div><strong>Watch simulator events</strong><p>Poll every 30 seconds. Reconcile correspondence if the recent-event window is exceeded.</p></div><input type="checkbox" checked={s.pollEnabled} onChange={e=>setS({...s,pollEnabled:e.target.checked})}/></label><label className="setting"><div><strong>Scheduled review</strong><p>Recheck records even when no event was observed.</p></div><input type="checkbox" checked={s.scheduledEnabled} onChange={e=>setS({...s,scheduledEnabled:e.target.checked})}/></label><div className="setting"><label>Every <input aria-label="Schedule interval in minutes" type="number" min="1" max="1440" value={s.intervalMinutes} onChange={e=>setS({...s,intervalMinutes:Number(e.target.value)})}/> minutes</label><select aria-label="Scheduled scan scope" value={s.scope} onChange={e=>setS({...s,scope:e.target.value})}><option value="documents">PGx correspondence</option><option value="sample">Sample cohort</option><option value="all">All patients</option></select></div><label className="setting"><div><strong>Execute accepted actions automatically</strong><p>The GP must accept each finding. The backend rechecks records before writing tasks, referrals, or PGx records.</p></div><input type="checkbox" checked={s.execute} onChange={e=>setS({...s,execute:e.target.checked})}/></label><button className="primary" disabled={disabled} onClick={()=>save(s)}>Save automation</button><div className="caution"><strong>Coverage is explicit</strong><p>Correspondence scans review patients with PGx mentions in GP-visible discharge documents. Full scans page through the complete patient directory and retrieve both GP and hospital records. Uninterpreted SNP panels do not become invented clinical diplotypes.</p></div></div>}
